### ISSUE TITLE
a bug that I cannot run the code

### ISSUE THREAD

**Issue by wty2333** [leftthomas/GatedSCNN#5]
when I finish the `creat_dataset(data_path)` and run the rest code, it raised an error

```
Traceback (most recent call last):
  File ".\train.py", line 129, in <module>
    optimizer)
  File ".\train.py", line 37, in for_loop
    for data, target, grad, boundary, name in data_bar:
  File "D:\python\install\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "D:\python\install\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\python\install\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "D:\python\install\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "D:\python\install\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\python\install\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\python\install\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\python\install\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\*\GatedSCNN1\dataset.py", line 48, in __getitem__
    grad_path = self.grads[index]
IndexError: list index out of range
```
i cannot find the mistake, can you help me?

**Comment by leftthomas** [comment]
@wty2333 you should use Linux, the path split is different on Windows
